### ISSUE TITLE
Multi-exchange

### ISSUE THREAD

**Issue by citec** [zertrin/clikraken#14]
Hi, I am using clikraken to trade in kraken, buy I want to use it to operate other exchanges. I am planning to develop an strategy pattern and put each API in a folder, letting a decorator choose the proper one depending on a new --exchange parameter. It is a quite easy solution and we could have a multi-exchange tool, where other collaborators could develop each API plugin.
What do you think? Should I go on my own (I will try/do it anyway) and create a new tool by forking this repo, or do you want me to PR and continue with that functionality here ?
I think I know how to do all the stuff easylly to get it done (new parameter, decorator and reestructure files, each exchange API in a folder)

**Comment by zertrin** [comment]
Hi thanks for this suggestion.

Let me a few days to finish merging/testing/documenting all the recent contributions (they came all at once, so I'm a bit taken by (good) surprise), and think whether I'd like to extend my version of clikraken to multi-exchange or if it would be better to fork.

I'll update you very soon.

**Comment by citec** [comment]
Hi @zertrin, did you have time to think about the multiexchange feature? I have noticed that many exchanges use the same type of authenticatino, tapi_nonce, etc, so it would be very easy to adapt it. I can do it, beginning with brazilian mecardobitcoin, that I need to integrate

**Comment by zertrin** [comment]
Hi @citec,

I have thought about it and decided that I prefer to keep clikraken itself just as it is. I won't have enough free time to oversee the changes needed to support multiexchange and anyway I have no way of testing the other exchanges myself.

You are welcome to create a fork of it which supports multiple exchanges. 

However I would kindly ask that you change the name of the fork to a name of your choosing to avoid confusion. As the name clikraken indicates, this tool is intended for the kraken exchange only.

I hope you understand this choice.

**Comment by citec** [comment]
ok, I will do that. Thanks for your time
