### ISSUE TITLE
I use your application with XBT in Kraken, but need use also with LTC (how use XBT and LTC by separate with differents accounts)

### ISSUE THREAD

**Issue by edudiy** [zertrin/clikraken#32]
Very very very excellent job, it´s very usefull   (I'm spanish, and my english is so and so).

With XBT is really perfect:

```
root@raspi:/home/pi# pyvenv ~/.venv/clikraken
root@raspi:/home/pi# source ~/.venv/clikraken/bin/activate
(clikraken) root@raspi:/home/pi# clikraken --csv balance
asset;balance
BCH;0.0000000000
DASH;0.0000000000
EUR;0.0000
LTC;2.2235517400
XBT;0.0560074100
(clikraken) root@raspi:/home/pi#
```

I can place buy & sell from 1 month ago with XBT. But now I want do a duplicate (clone) with LTC and execute in the same time the two but separate XBT of LTC. But I don´t know how. Only execute XBT, LTC show these errors:

```
mkdir -p ~/.ltc       # (Ok)
pyvenv ~/.ltc/clikraken         # (Ok)
source ~/.ltc/clikraken/bin/activate      # (Ok)
```

```
(clikraken) root@raspi:/home/pi/zuculum_ltc# clikraken --csv balance
Traceback (most recent call last):
  File "/usr/local/bin/clikraken", line 7, in <module>
    from clikraken.clikraken import main
  File "/usr/local/lib/python2.7/dist-packages/clikraken/__init__.py", line 1, in <module>
    from clikraken.__about__ import (
  File "/usr/local/lib/python2.7/dist-packages/clikraken/clikraken.py", line 12, in <module>
    from clikraken.api.api_utils import load_api_keyfile
ImportError: No module named api.api_utils
(clikraken) root@raspi:/home/pi/zuculum_ltc#
```

If you can help me? And if you need more info, please, contact me please.

Very very thks. I think than my ask is important for more people. In github I don't know as post this question.

T H A N K S    F O R   S H A R E  !!!

2º I don´t understand why XBT is correct and detect Python 3.5, but LTC in the same machine in other console detect Python 2.7 ?

3º I want use XBT with one account and LTC with other account. How I do this?

Thanks for all.

**Comment by citec** [comment]
Hi, the problem, I think, is that, when you are executing `pyvenv ~/.ltc/clikraken`, you are creating a virtualenv with python 2.7. Create a virtual env with python3.

But in any case, you don't need to install another environment to use two different accounts (if that's what you want to do). Just use the CLIKRAKEN_API_KEYFILE environment variable, like this:

`CLIKRAKEN_API_KEYFILE=~/.config/clikraken/kraken2.key clikraken place buy -p LTCEUR -t market 0.5`

I think that answers your 3 questions.

(P.S. I am spanish too, if you need a translation of my answer, just let me know)

**Comment by edudiy** [comment]
Hello, not problem with english. Thanks for response. I progress ;)

Now I launch clikraken without venv, but with the same configuration for all.

I'm trying to localize the archive con these environments variables:

CLIKRAKEN_API_KEYFILE

(Alternatively, you can set a path in the environment variable CLIKRAKEN_API_KEYFILE to override the default keyfile location)

CLIKRAKEN_USER_SETTINGS_PATH

(Alternatively, you can set a path in the environment variable CLIKRAKEN_USER_SETTINGS_PATH to override the default user settings file location)


If I change this, it change the others clikraken configurations in use?

Very very thanks


AUTO-RESPONSE:

    root@raspi:~/.config# CLIKRAKEN_API_KEYFILE=~/.config/clikraken2/kraken3.key clikraken balance
    asset      balance
    -------  ---------
    EUR        74.1729
    XBT         0.011

Excellent ;)        3 Consoles with 3 clikraken differents.  ;)

I repeat this line:   `~/.config#CLIKRAKEN_API_KEYFILE=~/`

**Comment by citec** [comment]
I have never used `CLIKRAKEN_USER_SETTINGS_PATH` env var, but, knowing the clikraken code a little, I guess that, if you execute only one instance of the code with that var (i.e.: `CLIKRAKEN_USER_SETTINGS_PATH=.... clikraken balance`), it will only affect that instance, the other running instances will continue unaffected

**Comment by zertrin** [comment]
In the way I planned it, yes, you would run the same script with different values for the environment variables.

For example:

```bash
# clikraken used wwith keyfile 1 and settings 1
CLIKRAKEN_API_KEYFILE=/path/to/keyfile1 CLIKRAKEN_USER_SETTINGS_PATH=/path/to/settings1.ini clikraken ....

# clikraken used wwith keyfile 2 and settings 2
CLIKRAKEN_API_KEYFILE=/path/to/keyfile2 CLIKRAKEN_USER_SETTINGS_PATH=/path/to/settings2.ini clikraken ....
```

If it's too bothersome to always put the env var in front, you can either:
* export different env vars in different shells (I suppose that's what you did)
* or write different wrapper scripts like this:

`clikraken_custom1.sh`:
```bash
#/bin/bash
export CLIKRAKEN_API_KEYFILE=/path/to/keyfile1
export CLIKRAKEN_USER_SETTINGS_PATH=/path/to/settings1.ini

clikraken "$@"
```

`clikraken_custom2.sh`:
```bash
#/bin/bash
export CLIKRAKEN_API_KEYFILE=/path/to/keyfile2
export CLIKRAKEN_USER_SETTINGS_PATH=/path/to/settings2.ini

clikraken "$@"
```
