### ISSUE TITLE
XBT sell & buy OK - Others coins with value very low ERROR

### ISSUE THREAD

**Issue by edudiy** [zertrin/clikraken#33]
Hello, I don´t understand what is the problem for this, XBT OK, XRP fail:

root@raspi:/home/pi# date
jue may  3 22:00:10 BST 2018

root@raspi:/home/pi# clikraken balance
asset         balance
-------  ------------
BCH        6.71e-06
DASH       0
EUR      675.3157
LTC        4e-08
XBT        0
XRP       50.00000286

root@raspi:/home/pi# clikraken place sell -t market -p **XXRPZEUR** 25
ERROR    - EGeneral:Invalid arguments:volume

root@raspi:/home/pi# clikraken place sell -t market 25 -p **XXRPZEUR**
ERROR    - EGeneral:Invalid arguments:volume

root@raspi:/home/pi# clikraken place sell -t market 25
ERROR    - EOrder:Insufficient funds

root@raspi:/home/pi# clikraken place buy -t market 25
ERROR    - EOrder:Insufficient funds

root@raspi:/home/pi# clikraken place buy -t market 0.002 -p **XXBTZEUR**
buy 0.00200000 XBTEUR @ market
OIYN2A-FUBDZ-B3SRLQ

root@raspi:/home/pi# clikraken place buy -t market 25 -p **XXRPZEUR**
ERROR    - EGeneral:Invalid arguments:volume
root@raspi:/home/pi#

Thanks for all

**Comment by citec** [comment]
have you checked if is there enough volume(buyers) in the books to fill your order? Maybe that's the reason

**Comment by edudiy** [comment]
### AUTO - RESPONSE

Kraken Trading Trading: Basics 

What is the minimum order size?

Ripple (XRP): 30
Bitcoin (XBT): 0.002
Bitcoin Cash (BCH): 0.002

https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-
