### ISSUE TITLE
Python error ?

### ISSUE THREAD

**Issue by edudiy** [zertrin/clikraken#34]
Hello, I'm trying exec clikraken in Ubuntu 16, 18 and Debian 9, but I find with this problem and don´t get a solution.

In Raspian for Raspberry PI 3 is OK, I use clickraken OK.

 root@Hive2 ~ # **pip install clikraken**
Collecting clikraken
  Using cached https://files.pythonhosted.org/packages/3a/60/08b819faec7f6ec61bab63daa80c5f1c54c187dc888693e5c6e63a87cd2e/clikraken-0.8.3-py2-none-any.whl
Collecting tabulate (from clikraken)
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Collecting arrow (from clikraken)
  Downloading https://files.pythonhosted.org/packages/e0/86/4eb5228a43042e9a80fe8c84093a8a36f5db34a3767ebd5e1e7729864e7b/arrow-0.12.1.tar.gz (65kB)
    100% |ââââââââââââââââââââââââââââââââ| 71kB 7.0MB/s
Collecting colorlog (from clikraken)
  Downloading https://files.pythonhosted.org/packages/69/eb/58ae10d3c46a0195ffdd0e3943d255d0d5029d71e5457785ecd665bcf0f3/colorlog-3.1.4-py2.py3-none-any.whl
Collecting krakenex<1.0,>=0.1 (from clikraken)
  Downloading https://files.pythonhosted.org/packages/64/2b/d1789bdf02cd83c2f20026dd1e998c09a2b7fe07ff1163cd1bea30c57ead/krakenex-0.1.4.tar.gz
Collecting python-dateutil (from arrow->clikraken)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac    100% |ââââââââââââââââââââââââââââââââ| 215kB 8.5MB/s
Collecting backports.functools_lru_cache>=1.2.1 (from arrow->clikraken)
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->arrow->clikraken)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: tabulate, arrow, krakenex
  Running setup.py bdist_wheel for tabulate ... done
  Stored in directory: /root/.cache/pip/wheels/2a/85/33/2f6da85d5f10614cbe5a625eab3b3aebfdf43e7b857f25f829
  Running setup.py bdist_wheel for arrow ... done
  Stored in directory: /root/.cache/pip/wheels/a3/dd/b2/d3b8d22e8136164c2e2c36ed42392531957cdf9c717065b28b
  Running setup.py bdist_wheel for krakenex ... done
  Stored in directory: /root/.cache/pip/wheels/a0/9d/91/cd287cdd166bf9a904dfa23b9021b1be1f41dc983877e2ec75
Successfully built tabulate arrow krakenex
Installing collected packages: tabulate, six, python-dateutil, backports.functools-lru-cache, arrow, colorlog, krakenex, clikraken
Successfully installed arrow-0.12.1 backports.functools-lru-cache-1.5 clikraken-0.8.3 colorlog-3.1.4 krakenex-0.1.4 python-dateutil-2.7.3 six-1.11.0 tabulate-0.8.2

root@Hive2 /usr/bin # **update-alternatives --config python**
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.5   2         auto mode
**1            /usr/bin/python2.7   1         manual mode**
  2            /usr/bin/python3.5   2         manual mode

Press <enter> to keep the current choice[*], or type selection number: 1

root@Hive2 /usr/bin # **clikraken**
Traceback (most recent call last):
  File "/usr/local/bin/clikraken", line 7, in <module>
    from clikraken.clikraken import main
  File "/usr/local/lib/python2.7/dist-packages/clikraken/__init__.py", line 1, in <module>
    from clikraken.__about__ import (
  File "/usr/local/lib/python2.7/dist-packages/clikraken/clikraken.py", line 12, in <module>
    from clikraken.api.api_utils import load_api_keyfile
ImportError: No module named api.api_utils

root@Hive2 /usr/bin # **update-alternatives --config python**
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.5   2         auto mode
* 1            /usr/bin/python2.7   1         manual mode
  **2            /usr/bin/python3.5   2         manual mode**

Press <enter> to keep the current choice[*], or type selection **number: 2**
update-alternatives: using /usr/bin/python3.5 to provide /usr/bin/python (python) in manual mode

root@Hive2 /usr/bin # **clikraken**
Traceback (most recent call last):
  File "/usr/local/bin/clikraken", line 7, in <module>
    from clikraken.clikraken import main
ImportError: No module named 'clikraken'

Can you help me? ...I don´t understand what is the problem. In Raspbian is perfect the installation and EXEC of clickraken.

Thanks for all

**Comment by zertrin** [comment]
You first pip command installed the packages in your python2 site-packages.

You need to use the pip coming from the python3 version.

Try with `pip3 install clikraken`

To check which python is used with pip, use `pip --version` (and `pip3 --version`)

**Comment by zertrin** [comment]
I couldn't not understand why the python2 version of pip accepted to install clikraken. It shouldn't be able. But I've just discovered that the latest release on PyPI has something wrong. The uploaded file is `clikraken-0.8.3-py2-none-any.whl` where it should be `clikraken-0.8.3-py3-none-any.whl`.

Will try to fix this now.

**Comment by zertrin** [comment]
Ok I have re-released 0.8.3 properly as 0.8.3.1. This should prevent Python 2 to manage to install clikraken.

In you case, better to first remove clikraken from your python2 site-packages properly (`pip uninstall clikraken`) and then install with the pip coming from python 3 (make sure with `pip --version` beforehand)

**Comment by edudiy** [comment]
Hello, weekend FREE.

I don´t understand you fully, but of other form OK --> clikraken EXEC OK . I explain my process after

You first pip command installed the packages in your python2 site-packages. You need to use the pip coming from the python3 version. Try with `pip3 install clikraken` To check which python is used with pip, use `pip --version` (and `pip3 --version`)

pip3 not found


==================== My Solution ==============

wget https://files.pythonhosted.org/packages/00/d7/c63096cdd021df99dc00c413f511af17b54388b154553a1eff109c009492/clikraken-0.8.3.tar.gz

tar xf clikraken-0.8.3.tar.gz

cd clikraken-0.8.3

python setup.py install

clikraken

OK


Very Thks for ALL. You are the BEST

**Comment by zertrin** [comment]
Yeah, that's another way to do it. However in that case it's not managed by pip.

In any case, you helped me see that version 0.8.3 was improperly packaged and I fixed it. So win-win in the end :)

**Comment by edudiy** [comment]
Hello, Thanks to you.

Share is the solution to all.

Are you contact with Kraken for your application ? It's great.

Are you spanish ? I'm live in Canaary Island (Tenerife), your friend "xXx"
in the page also is spanish.

Un saludo.

2018-07-10 3:40 GMT+01:00 zertrin <notifications@github.com>:
