### ISSUE TITLE
Python API is not really usable

### ISSUE THREAD

**Issue by martin-ueding** [zertrin/clikraken#39]
As it currently is, the project only provides a command line interface. Yet it also has an internal API that wraps the Kraken API. I have already tried to use the Python API in another project, but the handling of errors is not robust. It would be cool if the code was refactored such that the API could be exposed and used.

**Comment by flepied** [comment]
I tried to allow to use the API or CLI for some of the modules in my fork at https://github.com/flepied/clikraken . Let me know if it suits your needs.

**Comment by martin-ueding** [comment]
I've actually switched over to krakenex, which is used internally by clikraken. This has served me very well in my project.

**Comment by zertrin** [comment]
You are right, this project was really just meant for interactive CLI usage or light scripting. For full control of the API, krakenex is indeed the right choice.

I'll close the issue as this isn't really something that will be addressed (see #35) :wink:

**Comment by martin-ueding** [comment]
That totally makes sense. Incidentally I've started using krakenex for my project. I forgot to close the issue here.
