### ISSUE TITLE
Dedicated settings for ticker command

### ISSUE THREAD

**Issue by t0neg** [zertrin/clikraken#5]
Hi,

Ticker command is normally the most used command. I use it passing a list of pairs that i'm interested in:
`clikraken t -p XBTUSD,XBTEUR,ETHEUR,ZECEUR`

Would be good to have a dedicated setting - a list of currency pairs to watch especially for ticker command.
For example,
`ticker_currency_pairs=XBTUSD,XBTEUR,ETHEUR,ZECEUR`
In this case, command `clikraken t` should take list of pairs from config file if not explicitly specified.

BR,
t0neg

**Comment by zertrin** [comment]
Good idea, will implement it soon.

**Comment by zertrin** [comment]
Done in commit 6293e453b and released in version 0.6.0.

Thanks!
