### ISSUE TITLE
Private API not showing anything

### ISSUE THREAD

**Issue by ggrelet** [zertrin/clikraken#8]
Hi, the CLI seems to work very well with public information, but when I try to use the private API, the CLI doesn't respond anything, it just gives me back the _prompt_...

Any idea about that? I checked and double-checked my api keys..

**Comment by zertrin** [comment]
Can you give some more concrete details? Like which commands you actually tried, the result of `clikraken -V` and of `clikraken -h`?

**Comment by ggrelet** [comment]
Sure thing!
`clikraken -V` gives `clikraken version: 0.6.0`
`clikraken -h` gives the whole help section, exactly as described in your README.

I mostly tried `clikraken balance` or `clikraken b`. There simply is a second wait before I go back to the prompt. 

As I mentioned it, public API seems to work well, `clikraken ticker` gives:
`pair       last    high    low     vol     wavg  vol value      ask    bid`
`------  -------  ------  -----  ------  -------  -----------  -----  -----`
`ETHEUR  169.283  182.39  139.5  225434  160.861  36 MEUR      169.2    169`

Which correspond to the actual values (at the time I launched the command)

**Comment by zertrin** [comment]
Please include the content at the bottom of the output of `clikraken -h` to see **where** clikraken is looking for your key and settings on your computer. (`Create or edit the setting file ...`)

For me everything works as expected, so something on your end must be wrong.

**Comment by zertrin** [comment]
Oh and, I assume you do have a non-zero balance on your kraken account. I don't know what happens otherwise.

**Comment by ggrelet** [comment]
Here's my [clikraken -h.txt](https://github.com/zertrin/clikraken/files/1032555/clikraken.-h.txt)
And my [settings.txt](https://github.com/zertrin/clikraken/files/1032557/settings.txt)

And I do have zero balance!

**Comment by zertrin** [comment]
Well if you have no balance, there is nothing to show... So seems to me that the mystery is solved. 

Try to add currency to your account and create some orders, otherwise the private api has nothing to show.

**Comment by ggrelet** [comment]
@zertrin, thanks! Will do.

**Comment by ggrelet** [comment]
As a late response: adding currencies to my balance made the command to show it perfectly. Thanks for your great work!
